apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: {{ .Values.scaleway.containerRegistry }}/api:latest
        ports:
        - containerPort: {{ .Values.api.port }}
      imagePullSecrets:
        - name: container-registry-secret

---

apiVersion: v1
kind: Service
metadata:
  name: api-loadbalancer
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80          # Port exposed by the service internally within the cluster
      targetPort: {{ .Values.api.port }}  # Port exposed by the container, on which the service will send traffic to
      # nodePort: 30000   # Port exposed externally by the node
  type: LoadBalancer