apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-password
                key: password
        ports:
          - containerPort: {{ .Values.postgres.port }}
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: toque-postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: toque-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      nodePort: 30001   # Port exposed externally by the node
  type: NodePort
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-password
type: Opaque
data:
  password: {{ .Values.postgres.password | b64enc | quote }}
