apiVersion: v1
kind: Secret
metadata:
  name: container-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include (print $.Template.BasePath "/_dockerconfig.tpl") . | b64enc | quote }}
