apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-deployment
  labels:
    app: scanner
spec:
  replicas: 0
  selector:
    matchLabels:
      app: scanner
  template:
    metadata:
      labels:
        app: scanner
    spec:
      containers:
      - name: scanner
        image: {{ .Values.scaleway.containerRegistry }}/scanner:latest
      imagePullSecrets:
        - name: container-registry-secret