apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-deployment
  labels:
    app: scanner
spec:
  replicas: 0
  selector:
    matchLabels:
      app: scanner
  template:
    metadata:
      labels:
        app: scanner
    spec:
      containers:
      - name: scanner
        image: {{ .Values.scaleway.containerRegistry }}/scanner:latest
        env:
          - name: RABBITMQ_URL
            value: "amqp://guest:guest@rabbitmq-service:5672/"
      imagePullSecrets:
        - name: container-registry-secret