apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: {{ .Values.scaleway.containerRegistry }}/worker:latest
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-password
                key: password
          - name: DATABASE_URL
            value: "postgresql://postgres:{{ .Values.postgres.password }}@postgres-service:{{ .Values.postgres.port }}/db?sslmode=disable"
      imagePullSecrets:
        - name: container-registry-secret
