apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: marcbrunlearning/api:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: docker-cred

---

apiVersion: v1
kind: Service
metadata:
  name: api-loadbalancer
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80          # Port exposed by the service internally within the cluster
      targetPort: 8080  # Port exposed by the container, on which the service will send traffic to
      nodePort: 30000   # Port exposed externally by the node
  type: LoadBalancer