apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: marcbrunlearning/worker:latest
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-password
                key: password
          - name: DATABASE_URL
            value: "postgresql://postgres:$(POSTGRES_PASSWORD)@postgres-service:5432/db?sslmode=disable"
      imagePullSecrets:
        - name: docker-cred
